import { BadgeCheck, ChartSpline, LayoutDashboard, User } from "lucide-react";

export const items = [
  {
    title: "Dashboard",
    url: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    title: "Users",
    url: "/users",
    icon: User,
  },
  {
    title: "Statistics",
    url: "/statistics",
    icon: ChartSpline,
  },
  {
    title: "Subscriptions",
    url: "/subscriptions",
    icon: BadgeCheck,
  },
];

export const weeklyProgress = [
  {
    id: 1,
    name: "Grilled Chicken",
    mon: true,
    tue: false,
    wed: true,
    thu: true,
    fri: true,
    sat: true,
    sun: false,
  },
  {
    id: 2,
    name: "Veggie Burger",
    mon: true,
    tue: true,
    wed: true,
    thu: true,
    fri: false,
    sat: false,
    sun: true,
  },
  {
    id: 3,
    name: "Pasta Primavera",
    mon: true,
    tue: true,
    wed: true,
    thu: true,
    fri: true,
    sat: true,
    sun: false,
  },
  {
    id: 4,
    name: "Sushi Rolls",
    mon: false,
    tue: true,
    wed: false,
    thu: true,
    fri: true,
    sat: false,
    sun: true,
  },
  {
    id: 5,
    name: "Tacos",
    mon: true,
    tue: false,
    wed: true,
    thu: true,
    fri: false,
    sat: true,
    sun: false,
  },
  {
    id: 6,
    name: "Caeser Salad",
    mon: false,
    tue: true,
    wed: true,
    thu: true,
    fri: true,
    sat: true,
    sun: false,
  },
  {
    id: 7,
    name: "Beef Stir Fry",
    mon: true,
    tue: false,
    wed: false,
    thu: false,
    fri: true,
    sat: false,
    sun: true,
  },
  {
    id: 8,
    name: "Margherita Pizza",
    mon: false,
    tue: true,
    wed: true,
    thu: true,
    fri: false,
    sat: false,
    sun: true,
  },
  {
    id: 9,
    name: "Chicken Curry",
    mon: true,
    tue: true,
    wed: false,
    thu: false,
    fri: true,
    sat: true,
    sun: false,
  },
  {
    id: 10,
    name: "Fish and Chips",
    mon: false,
    tue: true,
    wed: false,
    thu: true,
    fri: true,
    sat: false,
    sun: true,
  },
];

export const monthlyProgress = [
  { id: 1, date: "01-12-2024", progress: 100 },
  { id: 2, date: "02-12-2024", progress: 95 },
  { id: 3, date: "03-12-2024", progress: 83 },
  { id: 4, date: "04-12-2024", progress: 100 },
  { id: 5, date: "05-12-2024", progress: 66 },
  { id: 6, date: "06-12-2024", progress: 1 },
  { id: 7, date: "07-12-2024", progress: 33 },
  { id: 8, date: "08-12-2024", progress: 79 },
  { id: 9, date: "09-12-2024", progress: 100 },
  { id: 10, date: "10-12-2024", progress: 14 },
  { id: 11, date: "11-12-2024", progress: 0 },
  { id: 12, date: "12-12-2024", progress: 67 },
  { id: 13, date: "13-12-2024", progress: 91 },
  { id: 14, date: "14-12-2024", progress: 8 },
  { id: 15, date: "15-12-2024", progress: 69 },
  { id: 16, date: "16-12-2024", progress: 34 },
  { id: 17, date: "17-12-2024", progress: 61 },
  { id: 18, date: "18-12-2024", progress: 85 },
  { id: 19, date: "19-12-2024", progress: 33 },
  { id: 20, date: "20-12-2024", progress: 92 },
  { id: 21, date: "21-12-2024", progress: 84 },
  { id: 22, date: "22-12-2024", progress: 77 },
  { id: 23, date: "23-12-2024", progress: 22 },
  { id: 24, date: "24-12-2024", progress: 90 },
  { id: 25, date: "25-12-2024", progress: 4 },
  { id: 26, date: "26-12-2024", progress: 6 },
  { id: 27, date: "27-12-2024", progress: 8 },
  { id: 28, date: "28-12-2024", progress: 29 },
  { id: 29, date: "29-12-2024", progress: 29 },
  { id: 30, date: "30-12-2024", progress: 76 },
  { id: 31, date: "31-12-2024", progress: 41 },
];

export const yearlyProgress = [
  {
    id: 1,
    name: "Grilled Chicken",
    progress: 91.6,
  },
  {
    id: 2,
    name: "Veggie Burger",
    progress: 66.4,
  },
  {
    id: 3,
    name: "Pasta Primavera",
    progress: 74.7,
  },
  {
    id: 4,
    name: "Sushi Rolls",
    progress: 58.1,
  },
  {
    id: 5,
    name: "Tacos",
    progress: 58.1,
  },
  {
    id: 6,
    name: "Caeser Salad",
    progress: 66.4,
  },
  {
    id: 7,
    name: "Beef Stir Fry",
    progress: 49.8,
  },
  {
    id: 8,
    name: "Margherita Pizza",
    progress: 58.1,
  },
  {
    id: 9,
    name: "Chicken Curry",
    progress: 58.1,
  },
  {
    id: 10,
    name: "Fish and Chips",
    progress: 58.1,
  },
];

export const features = [
  {
    id: 1,
    name: "Overview",
    value: "overview",
  },
  {
    id: 2,
    name: "Meal Plan",
    value: "meal",
  },
  {
    id: 3,
    name: "Inventory",
    value: "inventory",
  },
  {
    id: 4,
    name: "Cart",
    value: "cart",
  },
  {
    id: 5,
    name: "Chef AI",
    value: "chefAI",
  },
  {
    id: 6,
    name: "Socializing",
    value: "social",
  },
  {
    id: 7,
    name: "Extra Tokens",
    value: "extraTokens",
  },
];

export const plans = [
  {
    id: 1,
    name: "Free",
    price: 0,
    users: 441,
    trend: "+20.1% more than last month.",
    bgColor: "chart-1",
  },
  {
    id: 2,
    name: "Basic",
    price: 20,
    users: 343,
    trend: "+20.1% more than last month.",
    bgColor: "chart-2",
  },
  {
    id: 3,
    name: "Pro",
    price: 50,
    users: 268,
    trend: "-20.1% less than last month.",
    bgColor: "chart-3",
  },
  {
    id: 4,
    name: "Premium",
    price: 100,
    users: 192,
    trend: "-20.1% less than last month.",
    bgColor: "chart-4",
  },
];
